### ISSUE TITLE
No such module 'BraintreePayPal'

### ISSUE THREAD

**Issue by SheheryarShahVozye** [braintree/braintree_ios#1019]
### Braintree SDK Version

Braintree updated

### Environment

Both

### Xcode Version

14.2

### OS Version & Device

ios 16

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

I have installed brain tree via pods using following commands
	pod 'BraintreeDropIn', '8.2.0'
	pod 'Braintree/PayPal'
       pod 'Braintree'

But i am facing issue 'No such module 'BraintreePayPal' while importing. i need to integrate paypal into my iOS application.

### To reproduce

Install pod

pod 'BraintreeDropIn', '8.2.0'
	pod 'Braintree/PayPal'
       pod 'Braintree'

### Expected behavior

paypal item class and paypal payment class should work
<img width="1440" alt="Screenshot 2023-04-23 at 4 15 29 PM" src="https://user-images.githubusercontent.com/48985068/233836633-6d4dd2ba-fc22-4ae3-943f-8f6d46f95b45.png">

**Comment by KunJeongPark** [comment]
I believe that for Cocoapods, you only need to "import Braintree"

**Comment by scannillo** [comment]
Victoria is correct! You also don't need the additional lines `Pod 'Braintree'` and `pod 'Braintree/PayPal'` in your Podfile, since those come for free when you do `Pod 'BraintreeDropIn'` ([see Podspec](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn.podspec#L31)).

`import BraintreeDropIn` should suffice

Also, in the future - please open issues for Drop-In in the [Drop-In repo here](https://github.com/braintree/braintree-ios-drop-in).
