### ISSUE TITLE
Manual Install Errors

### ISSUE THREAD

**Issue by SolomonBier** [braintree/braintree_ios#102]
When manually installing the SDK, there are a few errors:

1. No labels on any of the rows (Credit card #, CVV, Exp date, etc.)
2. No ability to add a new card (the + button on the top right corner) after one card has been successfully added

Issue also seen by a different user below:
http://stackoverflow.com/questions/28669385/braintree-drop-in-controller-not-show-correctly?noredirect=1#comment45763878_28669385

**Comment by burnto** [comment]
Thanks. We're aware of this issue but haven't yet worked on it. Contributions of course welcome.

**Comment by SolomonBier** [comment]
@burnto  sorry-which is an issue. The lack of labels or no ability to add a new card? I'll try and add this but are there any known errors or bugs I should be aware of ?

**Comment by burnto** [comment]
Sorry, that could have been clearer. 

We were aware of the stack overflow question. It is very likely caused by a skipped or missing step in the manual integration doc. I suspect that the issue you're seeing with the button is the same problem or related, and I think it is likely that the manual integration doc needs to be updated.

Out of curiosity, why are you manually installing instead of using CocoaPods?

**Comment by SolomonBier** [comment]
@burnto I ended up installing via cocoapods-and that is where I am seeing the Venmo issue. So that one has nothing to do with manual install. Pods did fix this issue (forms without fields, etc.)

I avoided pods because AWS v.2.0.13 had a bug via pods that I couldn't solve (and they just realized/announced was a bug). I updated to their newest version and everything worked.

**Comment by elin-coursera** [comment]
@burnto I was having the same issue with missing labels. It appeared that the codebase expects the existence of "Braintree-UI-Localization.bundle", which is created as part of the CocoaPods build process. Since it isn't compiled when not using pods, what I did was create a new project that did use pods, built it, then searched my ~/Library/Developer/Xcode/DerivedData/project_name/Build/Products/Debug-iphoneos folder for the compiled bundles, which I then manually added to my project.

As for why we're not using pods, our app is setup using several Swift modules (each an individual project within our workspace), and it was just too much of a pain to get pods working without a million linker issues with our setup.

**Comment by burnto** [comment]
Thanks again @elin-coursera and @SolomonBier !

As mentioned in #80, we've updated the manual integration instructions, plus the way we're loading resources. See in particular bda0d8342e4930c4057ed872a5685c5ee7567a2a for relevant fixes. Please reply here if this doesn't resolve the issue to your satisfaction.

:palm_tree:
