### ISSUE TITLE
Manual integration problem: 'Braintree/BTUICTAControl.h' file not found

### ISSUE THREAD

**Issue by evgenyneu** [braintree/braintree_ios#110]
Hi, I am seeing this build error after implementing step four "Add the Braintree SDK code to project" from the [Manual Integration Without CocoaPods](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md) guide.

> braintree_ios/Braintree/UI/Braintree-Payments-UI.h:3:9: 'Braintree/BTUICTAControl.h' file not found

Any help would be appreciated.

## Tested in

* New Objective-C iOS app project.
* Xcode 6.1 (6A1042b) and 6.3 (6D543q)

Thank you

**Comment by burnto** [comment]
Hi @evgenyneu, thanks for letting us know about this issue.

I just updated the manual docs in 72ce3a803067bcb3d20455437859f48d2ecec799. I believe using the name `Braintree` instead of `Braintree SDK` for the framework target name will resolve this particular issue.

That said, we aren't happy with our manual integration, and we've been hearing multiple reports of developers having difficulty with it. If you _can_ use CocoaPods, it will handle all this complexity for you, which is why it's our recommended integration methods. Meanwhile, we're continuing to look at ways of making manual integration simpler. Any suggestions appreciated. 

And let us know if the docs change works for you.

**Comment by evgenyneu** [comment]
Thank you, renaming the target to `Braintree` allowed me to go past step four. I can not use CocoaPods, unfortunately. Thank you so much for your help!
