### ISSUE TITLE
Switching the default payment method but not show in Drop-in

### ISSUE THREAD

**Issue by shampire** [braintree/braintree_ios#146]
Hi Team,

I am a developer now working on iOS + PHP integration in sandbox enviroment in Hong Kong. 

Now what I want to do is show all the payment methods a customer used before and let him to choose for the next transaction. 

I have successfully fetch all the payment methods, however I find if a customer has use a PayPal account before, then the drop-in UI will still show the PayPal account first even I can set a credit card by use

$updateResult = Braintree_PaymentMethod::update(
 ‘credit_card_token',
 [
   'options' => [
     'makeDefault' => true
   ]
 ]
);

Actually I can see the this credit card is shift to the be the default one by

$paymentMethod = Braintree_PaymentMethod::find('token’);
$paymentMethod -> default (it is = 1)

So my question is can I directly show credit card as the default payment method in drop-in UI even the user used PayPal before?

Thanks!

**Comment by burnto** [comment]
Hi @shampire - thanks for reporting this.

The Drop-In UI displays the _most recently used_ payment method instead of the merchant-defined _default_ payment method. 

We are aware that this is a point of confusion (and, arguably, a shortcoming). 

We don't have immediate plans to change this behavior, but we've heard this feedback and will pay attention to this in future versions.

**Comment by gabro** [comment]
@burnto thanks for the explanation. I just faced this problem and it is incredibly confusing to me and apparently to anyone else has ever came across it.

If 100% of your users is confused by the behavior, I think you should **seriously** consider changing it.

**Comment by skunkworks** [comment]
Closing this, relevant discussion is in https://github.com/braintree/braintree_android/issues/23
