### ISSUE TITLE
BTBraintreeAPIErrorDomain Code=0

### ISSUE THREAD

**Issue by allen8300** [braintree/braintree_ios#149]
Hi there, I'm testing in live mode, and I kept getting this error when trying to pay by paypal and ApplePay.
Hope you can reply soon. Thanks in advance.

![img_0562](https://cloud.githubusercontent.com/assets/1751906/9013431/7c131f4e-37ee-11e5-8289-0e0185baa39c.PNG)

![screen shot 2015-08-01 at 1 43 00 am](https://cloud.githubusercontent.com/assets/1751906/9013458/b3c261a2-37ee-11e5-83c6-f12c0a8ac15e.png)

**Comment by skunkworks** [comment]
Hi, sorry to hear that you're having issues. Can you log into the Braintree Control Panel and verify under the **Processing** options that PayPal and Apple Pay are enabled for your account?

<img width="1200" alt="screen shot 2015-07-31 at 11 07 06 am" src="https://cloud.githubusercontent.com/assets/563375/9013990/5338a0a0-3774-11e5-9262-855f59ae19cd.png">

**Comment by allen8300** [comment]
Yes, all enabled. Any other guidance?

**Comment by skunkworks** [comment]
This is most likely a misconfiguration somewhere in the Control Panel. I suspect that the Apple Pay certificate and/or the Apple Pay Merchant ID may not be configured correctly, but there may be something more fundamentally wrong since PayPal is also failing for you.

Please reach out to support@braintreepayments.com, our support team can walk you through the debugging process.

**Comment by allen8300** [comment]
Er, all these basic configurations are already double checked. Any other guidance?
