### ISSUE TITLE
api.braintreegateway.com endpoint uses a weak security configuration

### ISSUE THREAD

**Issue by sergey-sportsetter** [braintree/braintree_ios#155]
Hey guys.

This is not directly related to Braintree iOS SDK per se, but with iOS 9 being right around the corner, it's worth noting.
When using a vanilla Braintree setup (with Drop-in UI), on iOS 9 β 5, I'm getting a generic error with this in my console:
```
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
```

It seems the default endpoint SSL certificate does not conform to [Apple's SSL Security requirements](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/#//apple_ref/doc/uid/TP40016240-CH1-SW2)

Currently, it's fixable with `NSExceptionRequiresForwardSecrecy` exception, but I'd rather have no security exceptions defined for my payment provider. 👀

I'm using your [xcode 7 branch](https://github.com/braintree/braintree_ios/tree/xcode-beta) with Xcode 7 β 6.

**Comment by burnto** [comment]
Thanks! We are definitely aware of this, and we have a fix coming!

**Comment by nixterrimus** [comment]
Any updates here?  We just had to ship our app for iOS 9 with an exception.

**Comment by skunkworks** [comment]
@nixterrimus Sorry for the inconvenience. The planned date for api.braintreegateway.com's SSL cert to be upgraded is at the end of the month. Unfortunately, since iOS 9 is shipping soon, we have to ask developers to add the exception until that change goes live. We will update this issue on GitHub when this is no longer necessary.

Please take a look at the [readme](https://github.com/braintree/braintree_ios/blob/master/README.md) for more info about the ATS exceptions, especially if your app integrates PayPal as a payment option.

**Comment by skunkworks** [comment]
The SSL certificate for api.braintreegateway.com was upgraded on 9/30, so there should no longer be a need for App Transport Security exceptions.
