### ISSUE TITLE
BTDropInViewController no longer showing email login for Paypal

### ISSUE THREAD

**Issue by orinmurphy** [braintree/braintree_ios#164]
Im displaying the BTDropInViewController in my app so users can add Paypal as a payment method.
Previously, it showed a login UI - email and password. 
But now it presents credit card input fields instead of the email login. 

![img_1445](https://cloud.githubusercontent.com/assets/3251360/9890424/d68bab28-5bcd-11e5-9215-9cd0120f87ec.PNG)

**Comment by skunkworks** [comment]
Resolved this issue -- I worked with Orin to update his integration to remove the drop in view controller and use BTPaymentProvider directly instead.

**Comment by orinmurphy** [comment]
@skunkworks hoping to jump on a screenhero with you at some stage to fix an issue. `Braintree.h` all of a sudden is `file not found`. If I comment that out, then the next Braintree file is also `file not found`. 
Im using cocoapods.

**Comment by skunkworks** [comment]
Hey @orinmurphy, sounds like there might be a project misconfiguration that's causing the Braintree pod framework/library to not be linked to the app. I'm going to be unavailable until Wednesday -- if the issue can't wait until then, please reach out to Braintree support (they're pretty awesome!). Otherwise, shoot me a message on Screenhero.

**Comment by orinmurphy** [comment]
@skunkworks thanks for getting back to me. I'm fine to wait until wednesday if that works.
