### ISSUE TITLE
Does the 4.0.0 requires bridging headers for swift?

### ISSUE THREAD

**Issue by nicpro85** [braintree/braintree_ios#196]
using 3.9.6 with swift you can import Braintree and then call Braintree(token...) on the 4.0.0 cannot import Braintree in swift

**Comment by intelliot** [comment]
Hi @nicpro85 -

Yes, 4.0.0 requires a bridging header, just like 3.9.6. The names of the files and classes have changed. Instead of importing Braintree, import BraintreeCore.h. Also, import the headers for components you want to access in Swift. For example:
```
#import "BraintreeCore.h"
#import "BraintreeCard.h"
#import "BraintreeUI.h" // For user interface components, including Drop-in
...
```

(Note that a bridging header is only needed if your project is not using frameworks.)
