### ISSUE TITLE
Possible crash with SFSafariViewController

### ISSUE THREAD

**Issue by keith** [braintree/braintree_ios#205]
We've started seeing a crash with the misuse of `SFSafariViewController` that _might_ be related to using braintree 4.0.2.

Here's the abridged log from fabric:

<img width="550" alt="screen shot 2016-01-07 at 11 01 19" src="https://cloud.githubusercontent.com/assets/283886/12179907/64170168-b52e-11e5-87fb-a66be5499ae1.png">

It looks like the code calling `SFSafariViewController` is in the closed source portion of this library so I can't tell if it could be the cause. We've since updated to BT 4.1.2 which will ship for us soon, so if we stop seeing the crash on that version I'll comment here.

**Comment by skunkworks** [comment]
Keith, thanks for reporting this. When I get a chance, I'll regression test 4.0.2 to see if I can duplicate this.

**Comment by skunkworks** [comment]
I'm having issues duplicating this crash with 4.0.2 or the latest version.

Based on the stack trace, this crash is caused by `BTPayPalDriver` initializing `SFSafariViewController` with an invalid URL. We are a bit puzzled how this can occur, so we need more info:

* How many crashes have you received via Fabric/Crashlytics?
* What kind of PayPal payments does the app support? (Future Payments / Checkout / Billing Agreements)
* On which devices and which versions of iOS is this crash occurring?

**Comment by keith** [comment]
- It's a relatively small number of crashes, just a few hundred across a few hundred of users (although I'm not sure about the percentage of users we have using paypal)
- We only use the SDK for logging in and creating a token (via `collectCardFraudData`)
- It looks to be 100% iOS 9, mostly iOS 9.2.0 but that's probably just skewed because our users are up to date

**Comment by skunkworks** [comment]
Hi Keith,

This crash you're seeing is rather puzzling -- we couldn't figure out a scenario where `SFSafariViewController` could be initialized with an invalid URL.

We need more data to isolate the issue, but in the meantime, we also don't want your users to experience crashes.

We've added 2bad50bed3a70b24bfc3a66afa10f93eb978a7cc to `master`, which adds a defensive check to prevent `SFSafariViewController` from being instantiated with bad URLs. Rather than crashing, your app will receive a `completionBlock` callback with an `NSError` so that you can display a friendlier message.

We've also added 1058894a5805a69e451f5b1843718f75b42959b5 to collect analytics events on our end when this occurs.

I'll do my best to get a tagged release out tomorrow. Please ping us back if you discover more.

**Comment by keith** [comment]
Awesome! Thanks for that. I'll update with the new release and I'll provide any more info if I can!

**Comment by skunkworks** [comment]
Just following up: we've released [version 4.1.3](https://github.com/braintree/braintree_ios/releases/tag/4.1.3) to prevent the crash from occurring, and we're hoping it will provide more insight into the root cause for the invalid URLs.

**Comment by keith** [comment]
Awesome! Thanks for that. I've updated our app and we'll see if we get any more crashes once it's released.

**Comment by skunkworks** [comment]
Feel free to re-open this issue if you continue to get reports -- I haven't seen any in our logs, although presumably your app that uses this version hasn't been released yet.

**Comment by keith** [comment]
:+1: yea our version with this should be out anytime now.
