### ISSUE TITLE
pay button loading indicator keeps spining (drop-in)

### ISSUE THREAD

**Issue by polis80cy** [braintree/braintree_ios#206]
This is for v3 SDK (swift2).

Using the drop-in, user clicks the "pay" button and button text transforms to a loading indicator. On the next view controller (e.g. 3D-Secure), the user clicks "cancel" (left navigation bar button). 3D-Secure view controller is dismissed and we are back to the initial drop-in view. The "pay" button still shows the loading indicator. How can you get it to display the initial "pay" text again?

**Comment by skunkworks** [comment]
Hi @polis80cy,

Can I get a little clarification on exactly how and where you're launching the 3D Secure verification? A code snippet would be nice. It seems like you're doing this in `dropInViewController:didSucceedWithPaymentMethod:`, but I want to verify first.

**Comment by skunkworks** [comment]
Hi again @polis80cy,

I think we've found the cause of the behavior you're seeing. Please take a look at e3ec77369405c5628aadf8d3a42b1f8a6a5b7167 and let us know if it fixes the behavior you're seeing.

We had a bit of a hard time duplicating this behavior because in our reference implementation, we dismiss the drop-in view controller in `dropInViewController:didSucceedWithPaymentMethod:`. Your app may not do this.

While hunting down your bug, we feel that the developer experience of integrating 3D Secure with Drop-in UI can be made a bit easier. For example, the drop-in view controller can make the call to `verifyCardWithNonce:`. We may tackle that feature in the future, if you're interested.

**Comment by polis80cy** [comment]
Hey @skunkworks, 

Thanks for looking at this so promptly.

Your fix did resolve the issue indeed, thanks. And you were right; I am not dismissing the VC, so that made it easier for me to spot.

I think you can make things a bit easier for sure when it comes to 3DS. I find the whole process a bit over-complicated than what it should have been.

**Comment by skunkworks** [comment]
Thanks for the feedback and for opening an issue. I've added a work item to our backlog to try to improve the 3DS experience with drop-in.

**Comment by polis80cy** [comment]
Great. And the snippet you asked for:

![screen shot 2016-01-12 at 23 55 40](https://cloud.githubusercontent.com/assets/14854276/12278508/356cf7fe-b98a-11e5-92ea-77391b8048c2.png)
![screen shot 2016-01-12 at 23 55 58](https://cloud.githubusercontent.com/assets/14854276/12278507/35693448-b98a-11e5-8a5a-e0ea927ffd80.png)
