### ISSUE TITLE
braintree run good on simulator but error on real device

### ISSUE THREAD

**Issue by dotcool** [braintree/braintree_ios#209]
'-(void)goPay

{
//    self.braintree = [[BTAPIClient alloc] initWithAuthorization:self.orderInfoModel.order.pay_code];
    NSString* clientToken =  self.orderInfoModel.order.pay_code;
    NSLog(@"token:%@",clientToken);
//    self.braintree = [[Braintree alloc] initWithClientToken:clientToken];
    _braintree = [Braintree braintreeWithClientToken:clientToken];
    NSLog(@"pay_code: %@",_braintree);
    [self tappedMyPayButton];
}

this code can run firmly good on simulator,and i pay two times success.
bu when i use the real device ,i just get nothing ..

this line "  _braintree = [Braintree braintreeWithClientToken:clientToken];" return _braintree = nil; so the screen is black ...please answer me soon.very 3ks.

**Comment by dotcool** [comment]
and when i use  

NSLog(@"version:%@",[Braintree libraryVersion]);


return  O2OMobile[292:20359] version:(null) 

help me i don't know what to do now

**Comment by skunkworks** [comment]
Are you using CocoaPods? `[Braintree libraryVersion]` only works if you are integrating with CocoaPods.

While debugging on a real device, add a breakpoint to `braintreeWithClientToken:` and step through the execution to see what the issue is. The `clientToken` may be `nil` or invalid -- you should see some errors in the debug console if this is the case.

**Comment by skunkworks** [comment]
Please feel free to reopen this issue if you're still dealing with this.
