### ISSUE TITLE
PayPal payment issue

### ISSUE THREAD

**Issue by cafuni** [braintree/braintree_ios#220]
I create a a drop in and when I pay with paypal, after click on sandbox blue button, the ui shows the payment method and after 2 seconds it close alone.
If I pay with credit card, no issue.

**Comment by skunkworks** [comment]
@cafuni Thanks for reporting this. I've duplicated this issue and will address it shortly.

**Comment by cafuni** [comment]
thank you... the issue is related only for paypal payments...  

    func dropInViewController(viewController: BTDropInViewController,
        didSucceedWithTokenization paymentMethodNonce: BTPaymentMethodNonce)
    {
        // Send payment method nonce to your server for processing
        
       }

the method starts without any user interaction...

**Comment by skunkworks** [comment]
@cafuni I may have misunderstood your original issue.

After clicking on the sandbox button, the drop-in view controller calls the `didSucceedWithTokenization` method with the PayPal account's payment method nonce. The sandbox flow does not require any further user interaction because it has already authorized a fake PayPal payment. In production, the user will be prompted to log in to PayPal, and there may be further user interaction required to authorize payment.

Hope that clears things up.

**Comment by cafuni** [comment]
I think that this behaviour is not a real use case to test... the UI should have the same behaviour in the sandbox... otherwise, how can I understand the functioning?

**Comment by skunkworks** [comment]
There are some technical issues that caused us to use a faked-out PayPal flow in our sandbox environment, but I agree with you -- we can do a better job with the PayPal testing experience in sandbox. It's certainly confusing that the UI is that different.

However, from a strictly functional perspective, the "mock" PayPal flow is enough to test the PayPal workflow between your app and our SDK: you make a method call to `BTPayPalDriver`, it performs an app switch or presents an `SFSafariViewController`, and you either get back a successful tokenization or a cancellation/error.
