### ISSUE TITLE
Using BTUI*View components in UIStackViews create a lot of unsatisfable constraints

### ISSUE THREAD

**Issue by donnellyk** [braintree/braintree_ios#237]
```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x12dd33150 BTUICardHint:0x12dd119b0.width == BTUIVisaVectorArtView:0x12dd16b80.width + 1>",
    "<NSLayoutConstraint:0x12d9f1dc0 'UISV-hiding' H:[BTUICardHint:0x12dd119b0(0)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x12dd33150 BTUICardHint:0x12dd119b0.width == BTUIVisaVectorArtView:0x12dd16b80.width + 1>
```

Hiding something in a UIStackView adds a ```UISV-hiding``` constraint with a priority of 1000, which conflicts with widths and heights sent by varies BTUIView components. I feel like, ideally, Apple would use some private super priority (1001) but in lieu of that I think the constraints within these components should be changed to 999 to not conflict.

Dup of https://github.com/braintree/ios-credit-card-form/issues/1 but it didn't seem like any work is being done on that repo.

**Comment by skunkworks** [comment]
Hi @donnellyk, thanks for the reporting this issue. We'll take a look at setting priority to 999 for our views -- if it doesn't cause any issues, we're 👍

**Comment by demerino** [comment]
Hi @donnellyk,

We've been looking into this issue and we're having a bit of trouble recreating the error. Could you share a snippet of how you create/use the `UIStackView` or point us towards an example that will allow us to recreate the error? Thanks!

**Comment by donnellyk** [comment]
It seems the unsatisfiable constraint only happens when the view is added to the `UIStackView` while `hidden = true`

```swift
let cvvField = BTUICardCvvField()
cvvField.translatesAutoresizingMaskIntoConstraints = false
cvvField.hidden = true
container.addArrangedSubview(cvvField)
```

That seems a bit more edge-casey then I originally thought, and this might just be a bug with stack views in general. I'm going to dig into a little more today and see what I find. Since I haven't seen Apple communicate anywhere that you should be using `priority = 999` everywhere when using stack views, seems weird if that was actually a requirement.

I've attached an example project, if that helps.
[Example.zip](https://github.com/braintree/braintree_ios/files/252675/Example.zip)

**Comment by demerino** [comment]
Thanks for the reply @donnellyk

I'm able to reproduce the issue now. In fact, if I add any hidden view to my `UIStackView` I am getting an error (even generic views). **I'm able to work around this issue by moving the code that populates my `UIStackView` with `hidden` views into (or after) the `viewDidAppear` method.**

Ex. If I create and populate the `UIStackView` in my `viewDidLoad` method, I get the errors. _BUT_, if I wait for the view to appear and then populate, it seems fine. Looks a bit fishy for sure. I think it has to do with the `UIStackView` and `UIView` having not been displayed yet, and trying to do 2 things at once when it finally appears.

Because this looks like an issue with Apple (any hidden views added before appearing seem to cause the constraint error) - I'm going to close these issues. But if you still feel like there is something that we can do, please respond or open another issue and we can dig deeper.
