### ISSUE TITLE
`presentApplePayFromViewController` not found in `BTApplePayClient`

### ISSUE THREAD

**Issue by eneko** [braintree/braintree_ios#251]
The latest docs regarding Apple Pay support indicate this method as available on BTApplePayClient, but that class does not contain such method.

    let applePayClient = BTApplePayClient(APIClient: client!)
    applePayClient.presentApplePayFromViewController(self, withPaymentRequest: paymentRequest, completion: { (applePayPaymentMethod, error) in
        if (applePayPaymentMethod != nil) {
            print("Show purchase alert w/ nonce: \(applePayPaymentMethod!.nonce)")
        }
    })

Drop-In Update
https://github.com/braintree/braintree_ios/blob/97eaa30eab50dfaa6efaf5e78145606eba9665d6/Docs/Drop-In-Update.md

BTApplePayClient
https://github.com/braintree/braintree_ios/blob/master/BraintreeApplePay/BTApplePayClient.m

**Comment by demerino** [comment]
Sorry for the confusion in the docs. We did remove this method just before the release and mistakenly left it in the docs. The docs will be corrected in the next release (either tomorrow or in the next week).

That being said, Apple Pay is still supported. Instead of using that method on `BTApplePayClient` - you can refer to our official docs on how to tokenize and process Apple Pay (basically you just have to present the `paymentRequest` yourself): https://developers.braintreepayments.com/guides/apple-pay/client-side/ios/v4

And thanks for trying the `Beta` - any other feedback is really appreciated! If there are missing features or customizations that you'd like to see - just open another issue.
