### ISSUE TITLE
Open blank page when we tap on the PAYPAL button on the BrainTree SDK PAYMENT SCREEN in iOS 10 only

### ISSUE THREAD

**Issue by meetdoshi1992** [braintree/braintree_ios#276]
When I tap on the PAYPAL button, I get one URL in the log. when I opened this URL into the browser, it works perfectly. But into iOS 10 devie, blank has been opened.

Please help me to resolve this issue.

And it works correcly into iOS 9.

**Comment by demerino** [comment]
I'm unable to recreate the issue on my iOS10 device.

Could you try a `Custom` Integration (don't use Drop-In) and try presenting the SFSafariViewController from the rootViewController?

```
[[[[UIApplication sharedApplication] keyWindow] rootViewController] presentViewController:safariViewController
                           animated:YES
                         completion:nil];
```

**Comment by demerino** [comment]
After further investigation - it seems that creating additional `UIWindows` can replicate this issue in iOS10. I'm not sure if that is the cause of your particular problem - but one possible solution is to display Drop-In from a new top level `UIWindow`.

```
        let braintreeClient = BTAPIClient(authorization: clientTokenOrTokenizationKey)
        
        let dropInViewController = BTDropInViewController(apiClient: braintreeClient!)
        dropInViewController.delegate = self

        dropInViewController.navigationItem.leftBarButtonItem = UIBarButtonItem(
            barButtonSystemItem: UIBarButtonSystemItem.cancel,
            target: self, action: #selector(ViewController.userDidCancelPayment))
        let navigationController = UINavigationController(rootViewController: dropInViewController)
    
        let dropInContainerRootController = UIViewController()
        let newWindow = UIWindow(frame: UIScreen.main.bounds)
        newWindow.rootViewController = dropInContainerRootController
        newWindow.makeKeyAndVisible()
        dropInContainerRootController.present(navigationController, animated: false, completion: nil)
        newWindow.windowLevel = 10 //or higher
```

Also - make sure you're using the most recent release of the SDK if possible (4.7.1 at the time of writing).

Let me know if this helps.

Oh - and I would like to suggest looking at our NEW Drop-In if you're targeting iOS9+: https://github.com/braintree/braintree-ios-drop-in

**Comment by aidanmorgan** [comment]
I am using the JS Client API (hosted as part of my website) which I load into a WebView using Xamarin.Forms and I am seeing the same behaviour.

There is no issue with PayPal on Android, however the PayPal page on iOS 10 initiates the process, a small circle spins, then a large spinner appears and then a blank page. It then sits there with no ability to move.

I am using the latest js library from https://js.braintreegateway.com/js/braintree-2.29.0.min.js

This issue is reproducible on an iPhone 5s (iOS 10.0.2) and iPhone 6SE (iOS 10.0.2)

**Comment by malleus** [comment]
I'm using the BTPayPalDriver to do a requestOneTimePayment, and encounter the same blank screen problem when I present the view controller in the BTViewControllerPresentingDelegate. Problem occurs on iOS 10. iOS 9 works fine.

However when I switched to present the viewcontroller from the rootViewController, it works again. the calling view controller is inside a UITabBarController, not sure if that causes the issue here.

**Comment by demerino** [comment]
Glad that this fix is working for everyone. We'll consider a fix within the SDK - but we're hesitant to create a `UIWindow`. We will investigate other ways to solve the issue.

**Comment by demerino** [comment]
`4.7.3` has introduced the ability to present `UIViewControllers` (in Drop-in) from the `Top View Controller`. In our tests, this solved some of the *blank* `SFSafariViewController` issues.

To ensure backwards compatibility, you'll need to opt-in to this behavior by setting `presentViewControllersFromTop` to `YES` on the `BTPaymentRequest`.

Comment on this issue or create a new one if you have feedback or can confirm that this resolves your issue.

**Comment by Pushpendra91** [comment]
I am facing same problem, I am using latest Sdk version.
