### ISSUE TITLE
Paypal Checkout error in iOS10.1.1

### ISSUE THREAD

**Issue by iad24** [braintree/braintree_ios#282]
I have integrated the braintree-paypal sdk to my iOS app. It is already in Appstore and is working fine. 
But when I used my iOS10.1.1 device, I cannot get a successful Paypal checkout.
Its working fine for devices running on iOS9.2 and iOS10.0.2

Below is the error msg I printed in the console:
![screen shot 2016-11-14 at 12 37 54 pm](https://cloud.githubusercontent.com/assets/15226261/20253573/abcd3cfa-aa67-11e6-96db-4bd07aca1eca.png)

Below is the error message on screen:
![whatsapp image 2016-11-14 at 12 42 41 pm](https://cloud.githubusercontent.com/assets/15226261/20253648/44848534-aa68-11e6-8d6f-d3a7c3337771.jpeg)

**Comment by demerino** [comment]
@iad24 

Some additional information can help us identify the issue:
- What version of the Braintree SDK are you using?
- Are you using Tokenization Keys or Client Tokens?
- What version of Swift are you using?

We appreciate any info you can share to help us pinpoint the integration and environment.

**Comment by JFejza** [comment]
Hi, I seem to be having a similar problem but with SDK version 3. Paul R. from the support advised me to post it here so you guys can check it out. Here is a short description:

The SDK is configured so that if the user has the Paypal app installed, it will perform an app switch to it using the URL scheme, handle login there and then return to our app, whereas if the app is not installed, it will just open a webview inside the app where the user can login and continue with the payment. 

But, with the latest update of the app we experienced an issue where the users who have the PayPal app are redirected to it but the login fails, even though the credentials are correct (they work if the PayPal app is launched separately and not using the app switch from Bouxtie app, and also on PayPal web, screenshot of the error attached). On the other hand, login also passes when the PayPal app is not installed and the webview is used instead

Here is the answer to the info questions:
1. What version of the Braintree SDK are you using?
**3.9.7**
2. Are you using Tokenization Keys or Client Tokens?
**We are using client tokens**
3. What version of Swift are you using?
**Swift 3.0**

Thank you for your assistance!

![screen2](https://cloud.githubusercontent.com/assets/7750855/20273179/9359e9ba-aa90-11e6-9e2b-115b307fe8e2.PNG)

**Comment by iad24** [comment]
@demerino 

What version of the Braintree SDK are you using? 
4.5.0

Are you using Tokenization Keys or Client Tokens?
Client Tokens

What version of Swift are you using?
2.3

**Comment by bluk** [comment]
@iad24 Can you please try again? It may have been a server side issue that has been corrected. We have tried a production account and cannot re-create the error.

**Comment by JFejza** [comment]
@demerino @bluk  Hey guys, did you maybe check this out about the info I posted? I have temporarily disabled the app switch as a quick fix, so it always opens the webview and it's successful, but I would be nicer if it would work with the native paypal app if the user has it installed.
Thanks!

**Comment by bluk** [comment]
@JFejza Thanks for the report. We are working with the native PayPal app team to fix the app switch issue (which seems to be different than the original issue reported for this issue). Right now, temporarily disabling the app switch is a good quick fix.

**Comment by iad24** [comment]
@bluk The issue is still there. Same error. =/

**Comment by ajaysinghthakur** [comment]
i am facing the same issue cannot checkout from PayPal 
![simulator screen shot 27-dec-2016 1 47 03 pm](https://cloud.githubusercontent.com/assets/8075509/21494972/fb8dd250-cc3a-11e6-9a19-d20529c6b9d7.png)

clicking on the proceed with sandbox purchase button its not getting back to app and no bounce received and no error received.

i am using Xcode 8 , swift 3. installed via carthage and braintree version  ~> 4.0.0

**Comment by varun-s** [comment]
Same issue as ajaysinghthakur in sandbox

**Comment by ajaysinghthakur** [comment]
i figure out removing method -
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool{

}
and using only older method -
// If you support iOS 7 or 8, add the following method.
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
  
}
it works but i don' know why these happens 
@varun-s

**Comment by demerino** [comment]
@ajaysinghthakur 

Thanks for sharing your solution. We'll investigate further and update our docs accordingly.

I'm closing this issue. Please create a new issue if you're still having problems.

**Comment by iad24** [comment]
@ajaysinghthakur Im already using: func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {

Buy anyways, I tried again. And the issue is not happening anymore. 
Still the same setting above and I did not add any code.
Most likely a server issue.
