### ISSUE TITLE
Test unsuccessful credit card verification

### ISSUE THREAD

**Issue by urska19** [braintree/braintree_ios#297]
Hi

I would like to test unsuccessful credit card verification using Visa 4000111111111115 on my app, but I am not able to do it. Function tokenizedCard returns no error. I receive nonce and payment is successfully completed. Following is my relevant code: 

       BTCard *card = [[BTCard alloc] initWithNumber:cardNumber expirationMonth:expirationMonth expirationYear:expirationYear cvv:cvv];
       BTCardClient *cardClient = [[BTCardClient alloc] initWithAPIClient: self.braintreeClient];
       [cardClient tokenizeCard:card completion:^(BTCardNonce *tokenizedCard, NSError *error) {
           NSArray *args = @[];
           if ( error == nil ) {
               if ( tokenizedCard ) {
                   completionHandler(tokenizedCard.nonce);
               } else {
                   completionHandler(args);
               }
           } else {
               args = @[error.description];
               completionHandler(args);
           }
       }];

I am using Braintree SDK version 4.3.2 with Sandbox.
Did someone come across something similar? Can someone help me figure out what am I missing?

Thanks.

**Comment by skunkworks** [comment]
Hi @urska19,

Don't forget to:

* Set [`BTCard` `shouldValidate`](https://github.com/braintree/braintree_ios/blob/master/BraintreeCard/Public/BTCard.h#L83-L88) to `YES`
* Make sure that you are using a Braintree client token as authorization for your `BTAPIClient`, since tokenization keys do not support verification
* [Enable card verification in your Braintree sandbox merchant account](https://articles.braintreepayments.com/control-panel/vault/card-verification#enabling-card-verification)

Hope that helps! Feel free to reopen if you continue to have issues.

**Comment by urska19** [comment]
Thank you @skunkworks. That was it. :)
