### ISSUE TITLE
BTUICardFormView dismiss keyboard and jump to next field

### ISSUE THREAD

**Issue by ehabsaifan** [braintree/braintree_ios#306]
#### Developer Info

- Braintree SDK version:

- Integration type and version:

- Environment:

#### Issue Details
> 1. The CVV field should be before the postal Code.
> 2. Auto jump to next field doesnt work after postal code.. Basically I should touch one of the above two fields then put info again to jump to the cvv field. 
> 3. There should be automatic dismiss for the keyboard.
> 4. Poor documentation on "[http://cocoadocs.org/docsets/Braintree/4.7.3/index.html]" most of the writing in black and I cant see anything.
> 5. Should support Swift.
> 6. Every time I run the app on Xcode Version 8.2.1 I have to Clean the product to be able to run the app.

![img_0172](https://cloud.githubusercontent.com/assets/10765483/21827836/369134ac-d742-11e6-99fc-fef21a16ce42.PNG)

**Comment by demerino** [comment]
Thanks for all of the feedback @ehabsaifan 

We have a fix coming out for the docs issue (black text).

What specific issues are you having with Swift? It should work correctly.

Lastly, I wanted to point you towards our *new* Drop-in. We're in the process of deprecating this version of Drop-in. You can learn more about the new Drop-in and see Swift examples in our official guide (with better documentation): https://developers.braintreepayments.com/guides/drop-in/ios/v4

It is also supports 23 languages!

Let me know if you're still having issues.

**Comment by ehabsaifan** [comment]
Hi David Merino,

**Comment by ehabsaifan** [comment]
Also it would be nice to have a CardValidator class and access to the individual text field (Card #, CVV, Experation date) for verification using this class

**Comment by demerino** [comment]
@ehabsaifan Thanks for the additional feedback!

- You can see the Swift documentation for the *new Drop-in* by clicking the `Swift` button above a code snippet on the docs: https://developers.braintreepayments.com/guides/drop-in/ios/v4

Example:
![tap-swift](https://cloud.githubusercontent.com/assets/7817434/21836660/c86a00aa-d77b-11e6-9e86-d74ef534a86f.png)

And we do expose every text field and card validation in our *new Drop-in* so that you can build your own version if you want to. These links might be helpful to get you started:

- Card Validation: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKCardType.h#L5-L28
- Card Number Input: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKCardNumberFormField.h
- CVV Input: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKSecurityCodeFormField.h
- Expiration Input: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKExpiryFormField.h

Let me know if you're still having problems with these new classes or need to update them for your needs.
