### ISSUE TITLE
Apple pay not showing NEED HELP

### ISSUE THREAD

**Issue by adriansalim** [braintree/braintree_ios#317]
how to show apple pay?
i already change my region using change proxy and i already tried using vpn in my iphone but still cant show that button
my region in indonesia but that apps will be use in singapore
is there any configuration to show that button?
![screen shot 2017-03-10 at 3 06 53 pm](https://cloud.githubusercontent.com/assets/24728715/23787147/3927596e-05a3-11e7-9cc2-ea2836559926.png)
![screen shot 2017-03-10 at 3 07 23 pm](https://cloud.githubusercontent.com/assets/24728715/23787164/4cc0f282-05a3-11e7-8694-9a82a96e8bc9.png)

**Comment by meismyles** [comment]
Apple Pay is enabled by default if your configuration is setup correctly, your drop-in is initialised correctly and the device/simulator you are running on supports it.

Aside from posting your code, have you setup your Apple Pay certificates correctly? Have you enabled Apple Pay in the Braintree web portal? Once you log in, it is in Settings > Processing, and there should be an area that says 'Accept Apple Pay'. Make sure this is enabled here or it will not show in-app using the drop-in.

I'd also advise probably [contacting their support through here](https://developers.braintreepayments.com/forms/contact) rather than posting in this issue tracker. They seem to respond much quicker and since it's a configuration issue you have rather than an actual SDK issue/bug you are reporting, they are probably more suited to help you.

**Comment by crookedneighbor** [comment]
@meismyles is correct. This is unlikely an issue with the code base, so your best bet is to [contact support](https://developers.braintreepayments.com/forms/contact). I'm going to close this issue, but re-open it if necessary.
