### ISSUE TITLE
How to get payment method token from drop-in UI?

### ISSUE THREAD

**Issue by coolbeet** [braintree/braintree_ios#384]
How to get payment method token from drop-in UI? Seems I can only get payment method nonce from the result object.

**Comment by demerino** [comment]
The iOS client will only return a nonce. You can use the nonce on your server to find/create a payment method token. Learn more on our docs site: https://developers.braintreepayments.com/reference/request/payment-method/create/ruby#examples

**Comment by coolbeet** [comment]
@demerino Hi we just contacted Braintree Technical Support, they said: `PaymentMethod.create()` will not work, that API call does return a token when given a nonce, but it is always a new token.

Is that true? We tested on sandbox and seems it does return the existing token.. Could you confirm it?

Thanks a lot!

**Comment by demerino** [comment]
Thanks for contacting Braintree Technical Support.

I think it is best to continue this discussion via that channel and clarify how you wish to use the `token` and what your results in `sandbox` show you. The link I referenced to `PaymentMethod.create()` was one example of how to create/receive a token. You will want to review all relevant documentation ( e.g. https://developers.braintreepayments.com/reference/request/payment-method/create/ruby#preventing-duplicate-payment-methods ) to decide which solution works best for you.

**Comment by coolbeet** [comment]
Thanks for the detailed explanation. Though I could probably have phrased my question more clearly.

Here's my use case:
* I have several existing payment methods in the Vault for an existing customer.
* My iOS client displays those payment methods and prompts this customer for a selection.
* When the customer makes a selection, my server would like to store a handle of the selected payment method in my database for recurring charges in the future. However, the iOS SDK only allows the client to get a nonce for the selected payment method, which cannot be used for recurring charges. Therefore, the client will send my server the nonce, and I need to find a way for my server to get a payment method token from that nonce.

Thus, my question is, assuming that the payment method that I'm retrieving already exists in the Vault (created in some other workflow), if I pass a nonce (pointing at this existing payment method) to PaymentMethod#create along with the customer_id, will PaymentMethod#create simply return the existing payment method in an idempotent approach? 

In addition, is there another (better) way to get a payment method token from a nonce for an existing payment method?

Your help is very much appreciated, and we thank you for your time!

**Comment by skunkworks** [comment]
Hi @JSilversun, can you clarify what you mean by "pay with the same card multiple times"? To be more specific, what are the API calls you are making? And can you link to the specific documentation you're referring to?

This will help greatly.

**Comment by skunkworks** [comment]
Hi @coolbeet, I think I understand the use case you're trying to solve here. If the recurring charges you're trying to make are along the lines of a subscription model, you may want to look into using Braintree's [Recurring Billing](https://developers.braintreepayments.com/guides/recurring-billing/overview) feature. It is possible to [create a subscription using a payment method nonce](https://developers.braintreepayments.com/reference/request/subscription/create#payment_method_nonce).

However, it sounds like the recurring charges you're referring to are unplanned (i.e. not at a regular interval) and initiated by the customer (since it's selected by the customer on the client-side). In your particular setup, I see your problem: the customer selects a payment method in your UI that's stored in the Braintree Vault, the Braintree iOS SDK provides you the nonce for that payment method, and your server needs to create more than one transaction but cannot because nonces are always single use.

The best way to solve this is to fetch the [customer's payment methods](https://developers.braintreepayments.com/reference/response/customer#payment_methods) from your server rather than through the client SDK. You should be able to replace the call to `fetchPaymentMethodNonces:` with a method that makes an API call to your server, and your server can look up the Braintree `Customer` and return their payment methods to the client.

Just a note about the above: this could be optimized by storing the payment method tokens on your server (e.g. in a database), which would remove an extra API call to Braintree to fetch the customer's payment methods.

**Comment by JSilversun** [comment]
@skunkworks Hi, let me explain you our situation: We have an e-commerce with regular and subscription products but, subscriptions are handled by another payment gateway Chargebee, who needs the payment method token from braintree. 

Our platform works like this: Our client side shows all payment methods from the customer, he selects the payment method  he wants and the client side generates the token and pass it to the backend, then we **always** use `PaymentMethod.create()` with our customer id and the token from the client side, because if there is a subscription in the cart we need the **payment method token** so we can use it in Chargebee, my question is if we use `PaymentMethod.create()` with a payment method that already exists, Braintree retrive the existing payment method or creates a new one? I couldn't find something in the documentation that says this method works like "get or create", actually it says 

> PaymentMethod.create()
To create a **new payment method** for an existing customer, the only required attributes are the customer ID and payment method nonce.

And yet in the previous answers on this issue says

> he link I referenced to PaymentMethod.create() was one example of how to create/receive a token

When we test our application manually it doesn't seem to duplicate the payment method every time, but when we apply our unit test with a 'fake-valid-nonce' it always duplicate the payment method, I'm not sure if this is a braintree bug or a documentation issue. Thanks for your time !

**Comment by skunkworks** [comment]
Hi @JSilversun,

`fake-valid-nonce` and the other test nonces behave differently with `PaymentMethod.create()`, and it is expected that they will return a brand new payment method (token). It's similar to the behavior of a payment method nonce from a single-use, non-vaulted payment, e.g. the customer enters a new credit card and neither your client or server store that in the Braintree vault.

The payment method nonces from the vault currently have undocumented behavior where `PaymentMethod.create()` will return the backing payment method and will not create a duplicate. Because this is undocumented behavior, we can't guarantee that it won't change at a future date, although we're very conscientious of making changes that might break merchant integrations.

The canonical best practice for your use case is what I mentioned in my previous reply, which is to fetch customer payment methods from your server. However, your solution does work, but it won't work with our static test nonces because they're not backed by a vaulted payment method.

I'll bring this up as a point of discussion with the team to see if we can make any improvements.
