### ISSUE TITLE
Off-line credit card validation

### ISSUE THREAD

**Issue by andreaperizzato** [braintree/braintree_ios#396]
Hi,

when building a custom card payment UI, there is currently no way to validate the credit card number  and infer the card type offline without using the BraintreeUI framework. 

With `BraintreeCard`, the only way to validate a card is to tokenize it and inspect the [BTCardNonce](https://github.com/braintree/braintree_ios/blob/master/BraintreeCard/Public/BTCardNonce.h) passed to the callback [here](https://github.com/braintree/braintree_ios/blob/master/BraintreeCard/Public/BTCardClient.h#L61).

The `BraintreeUI` framework has [BTUICardType](https://github.com/braintree/braintree_ios/blob/master/BraintreeUI/Models/BTUICardType.m) which is used by all input fields to validate card details. However, this class is not public.

My proposal would be to move `BTUICardType` in `BraintreeCard` renaming and making it public so that it can be used. Stripe has a [similar feature](https://github.com/stripe/stripe-ios/blob/b4e3e731b784c7a772a23ebddeab7e8e86c14a6e/Stripe/PublicHeaders/STPCardValidator.h).

What do you think? 
I could potentially submit a PR if you are happy with this change.

We are currently using Braintree to process payments with a custom UI and still need to import other big frameworks only to do offline validation.

### General information

* SDK/Library version: 4.14.0

**Comment by bluk** [comment]
Hello! Have you tried looking at `BraintreeUIKit`, specifically [BTUIKCardType](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKCardType.h) to see if it meets your needs? It is in the latest [iOS Drop-in repository](https://github.com/braintree/braintree-ios-drop-in) and you can just dependent on [BraintreeUIKit](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn.podspec#L37) instead of all of Drop-in.

**Comment by andreaperizzato** [comment]
Great, thank you so much!

Feel free to close this issue if you are not planning to make it public in this framework.

**Comment by bluk** [comment]
Glad it works. The `BraintreeUI` module in this repository is for an older version of Drop-in so we don't plan on making non-critical updates to it. The newer `BraintreeUIKit` should be used for new integrations. Thanks.
