### ISSUE TITLE
Security concern about saving payment method token

### ISSUE THREAD

**Issue by delphiy** [braintree/braintree_ios#440]
Hi,

Where is the best place to save method payment token?

I am currently save them into shared preferences for both IOS and android .  For example, customer click checkout , I am calling my server to get customer payment methods , then customer click pay . I am using payment method token to create nonce token and make transaction . 

On the server , I am only check if header of api call contains permission . My concern is , if anyone have customer id and payment method token , will use them illaglly .

What is the best practice ?

Many thanks

**Comment by skunkworks** [comment]
If your server is checking the API header for the client user authentication, and your client authentication strategy is secure, then it should not be an issue to expose the customer ID and payment method token.

The customer ID and payment method token are not sensitive data because they can only be used to make calls to the Braintree API with your Braintree API keys. As long as you protect your private API key _and_ your server API endpoints are using a secure authentication and authorization strategy, there shouldn't be any vulnerabilities.

What is the purpose of saving the payment method token on the client? Are you trying to set a default payment method?

**Comment by delphiy** [comment]
thanks for response ,
yes , I  want to set default payment so customer does not enter payment again. No problem at that .

my backend server is firebase ,

I only check for user firebase token , in other words checking if user is logged in  .

if hacker has firebase user token , he will call backend and have payment methods response and again create transaction using firebase token and payment method token.
 

in my client apps andriod and Ios .

I am sending nonce token with firebase token to server . Server do the following :

1 - check firebase token 
2 - make operation using nonce token with braintree

**Comment by skunkworks** [comment]
Assuming that the Firebase user token is appropriately secured, I don't see any potential security issues with your approach. However, persisting the payment method token on the client side can be problematic in some cases, for example, if the card expires or the customer gets a new card number. I'd recommend a balance between customer convenience (a fast checkout experience) and customer flexibility (ability to choose a different payment method). Hope that helps.
