### ISSUE TITLE
 Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_FBSDKError", referenced from:       _OBJC_CLASS_$_FBSDKShareError in FBSDKShareKit(FBSDKShareError.o)       objc-class-ref in FBSDKShareKit(FBSDKLikeActionController.o)   "_OBJC_METACLASS_$_FBSDKError", referenced from:       _OBJC_METACLASS_$_FBSDKShareError in FBSDKShareKit(FBSDKShareError.o) ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Abhishek54321** [braintree/braintree_ios#448]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by Abhishek54321** [comment]
I am not able to resolve this issue.If help from ,its really appreciable .

**Comment by Epreuve** [comment]
@Abhishek54321 This error looks to be related to missing classes related to the Facebook SDK, rather than anything to do with the Braintree SDK.  You'll want to refer to their repo for the project [here](https://github.com/facebook/facebook-objc-sdk) to request assistance with resolving issues with their SDK.
