### ISSUE TITLE
Integrate SDK without pods

### ISSUE THREAD

**Issue by maulikpat** [braintree/braintree_ios#476]
Hello,

Is there any document or a way to integrate SDK to project without using cocoa pods?

**Comment by scannillo** [comment]
Hello,

The two ways we document integrating our SDK into your project is via CocoaPods or Carthage. You can find instructions on both of them [here](https://github.com/braintree/braintree_ios#installation). 

Following one of these patterns helps us troubleshoot your integration if need be.

**Comment by maulikpat** [comment]
@scannillo  So we can not integrate this directly? I don't want to have xcode workspace files so.

**Comment by scannillo** [comment]
Hello @maulikpat . I recommend you use Carthage. It [doesn't modify your Xcode project](https://www.raywenderlich.com/416-carthage-tutorial-getting-started) or force you to use a workspace.  

We encourage using a dependency management tool since it will be easier for you to stay up to date on new releases to our SDK, instead of cloning our repo every release and manually including it in your project each time. We also won't be able to provide the same troubleshooting support for this integration.
