### ISSUE TITLE
Deprecated UIApplication API usage

### ISSUE THREAD

**Issue by WojciechTrzasko** [braintree/braintree_ios#500]
### General information

* SDK/Library version: 4.30.1
* Environment: Sandbox/Production
* iOS Version and Device: iOS 13 and above
* Integration type and version: CocoaPods 1.8.4

### Issue description

Hi,

With the introduction of iOS 13, some parts of `UIApplication` were marked as deprecated. Based on that we would like to fix such issues in our project as soon as possible, so in one of the investigations we found out that `BTDropInUtil` is still using a `keyWindow` property.

So I would like to ask if resolving this in your pipeline?

**Comment by scannillo** [comment]
Hi @WojciechTrzasko. Thanks for bringing this to our attention. I will add this to our team's backlog and will post here when we update.

**Comment by WojciechTrzasko** [comment]
Hi @scannillo ,
Thanks for the quick reply and for adding above to your backlog.

As goes for the timeline, in general, we are preparing our app for MVP release in the middle of December. This is a very crucial date for us. We are also aware that Apple already started to return errors or warnings about usage of deprecated UIWebView API and we are a little bit afraid that similar situations could happen with the above deprecations. This is why we are trying to reduce such risks.

Do you think that you will be able to check this (or even better to resolve it) before the middle of December? 

PS. At the same time, I'm very sorry that we can't offer you our help with some PR, but unfortunately, we are just overwhelmed by the work in the project 😞 .

**Comment by scannillo** [comment]
See same [response](https://github.com/braintree/braintree-ios-drop-in/issues/197#issuecomment-557118423) in `braintree-ios-drop-in`.

**Comment by sestevens** [comment]
Hi @WojciechTrzasko, we're working on cleaning up the deprecated API usage in Braintree Drop-in, but we noticed that in this issue you're referring to a warning in `BTDropInUtil`, which is part of a deprecated module, `BraintreeUI`. Since this entire module is deprecated, we don't recommend including it in your project.

I'm going to close out this issue since we are no longer making updates to `BraintreeUI`. We will update [the issue you opened in the Braintree Drop-in repo](https://github.com/braintree/braintree-ios-drop-in/issues/197) when we've released a new version cleaning up the deprecated APIs used there.
