### ISSUE TITLE
The SSL related error occur when I am trying test on Sandbox 

### ISSUE THREAD

**Issue by raviprajapat1** [braintree/braintree_ios#524]
- SDK/Library Version: 4.33.0
 - Environment: Sandbox
 - iOS Version: iOS 13.1
 - Device iPhone 11 Pro Max
 - Integration type & version CocoaPods 1.9.1

**Describe the bug**
Below error it thrown by the framework when I am trying to add card using Sandbox evironment
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9858, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x600002397e40 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.sandbox.braintreegateway.com:443/merchants/zmvj4cy44gb2yzpz/client_api/v1/payment_methods/credit_cards, NSErrorFailingURLStringKey=https://api.sandbox.braintreegateway.com:443/merchants/zmvj4cy44gb2yzpz/client_api/v1/payment_methods/credit_cards, _kCFStreamErrorDomainKey=3}

**To Reproduce**
1. Tap on add 'Credit or Debit Card'
2. Enter sandbox card info 4111 1111 1111 1111 and exp. date 20/2021
3. See error

**Expected behavior**
It shouldn't give error.

**Comment by sestevens** [comment]
Hi @raviprajapat1 👋 The sandbox SSL certificates used by older versions of Braintree iOS (4.9.6 and earlier) were rotated in April. This change also impacts version 6.0.0 and earlier of Braintree iOS Drop-in. You mentioned that you're using version 4.33.0 of Braintree iOS, which should not be impacted, but you may want to double-check that version and/or the version of Drop-in (if you're using it).

If you're using an older version of the SDK, you'll need to update by **May 18** since the SSL certificate change will be coming to production as well.

If you are indeed using version 4.33.0, please let me know and we'll continue investigating this issue on our end.

**Comment by raviprajapat1** [comment]
Thanks for prompt reply, I correct my mistake by upgrading to the latest version. 

It would be great if you can do some help for manually integration of the 'BraintreeDropin'. 

I tried [Manual integration](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md) after I integrated this, I got an runtime exception 

**_dyld: Library not loaded: @rpath/CardinalMobile.framework/CardinalMobile
  Referenced from: /Users/apple/Library/Developer/Xcode/DerivedData/BTDemo-gqoraqrbxqydhvgcrfgmijavczfd/Build/Products/Debug-iphonesimulator/Braintree.framework/Braintree
  Reason: image not found_** 

Looking forward to hear from you:)

Thanks in Advance!!!

**Comment by raviprajapat1** [comment]
Resolved the runtime exception by just adding CardinalMobile.framework in BrainTree(Target) > General > Framework & Library.
