### ISSUE TITLE
After integrating braintree sdk manually I stucked, I can not use module UIKit.

### ISSUE THREAD

**Issue by raviprajapat1** [braintree/braintree_ios#525]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 4.33.0
 - Environment: Sandbox
 - iOS Version: iOS 13.1
 - Device: iPhone 11 Pro Max
 - Integration type & version : Manually

**Describe the bug**
I am unable to use UIKit components after integrating Braintree sdk manually even in POC, It would be great if anyone can help me on this.

**To Reproduce**
1. Followed all the step of [Braintree Manual Integration](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md)
2. Then try to use BTDropInViewControlller
3. I am unable to present this controller because of not able to access presentViewController method of UIViewControlller (since UIKit component not loaded)

**Expected behavior**
I should able to use UIKit component.
<img width="307" alt="Screen Shot 2020-05-01 at 11 20 20 AM" src="https://user-images.githubusercontent.com/12083717/80785644-963e9980-8b9e-11ea-9ff6-73611acb8fb2.png">

**Screenshots**

**Comment by scannillo** [comment]
The screenshots you provided don't point to an issue with any class in the `Braintree` module. Also, to present the `BTDropInController` you'll want to use our [Drop In SDK](https://github.com/braintree/braintree-ios-drop-in), instead.

Also - have you considered using [Carthage or CocoaPods](https://github.com/braintree/braintree_ios/#installation) instead of manual integration? We recommend either as it helps us in debugging your issues, and makes updating your SDK version much easier (which is something we suggest doing frequently).

**Comment by raviprajapat1** [comment]
I am agreed with using Cocoapod or Cathage but my app requirements is manual integration. If you could provide any document for manual integration of the [Drop In SDK](https://github.com/braintree/braintree-ios-drop-in).

**Comment by scannillo** [comment]
We don't have an equivalent set of docs written up for Drop In manual integration, because it isn't something we encourage or officially support. Though, the process would be similar to the doc you linked for Braintree SDK, but instead to only include the Braintree Drop In SDK.

I encourage you to check out [Carthage](https://github.com/Carthage/Carthage), if possible. 
> Carthage builds your dependencies and provides you with binary frameworks, but you retain full control over your project structure and setup. Carthage does not automatically modify your project files or your build settings.
