### ISSUE TITLE
Cordova implementation its posible 

### ISSUE THREAD

**Issue by patrykKlimczak** [braintree/braintree_ios#551]
**Is your feature request related to a problem? Please describe.**
Create app of native framework7 (vue) with dropin braintree Javascript, but apple store not allow to push app with only card payments so I need apple pay subscription in my cordova app.

**Describe the solution you'd like**
I need use subscription payment base on braintree with apple pay options on app cordova (framework7)

Do you have maybe any solutions?

**Comment by scannillo** [comment]
Hello @patrykKlimczak - I think you meant to propose this feature request in the https://github.com/braintree/braintree-web repository, so I will close this issue. Our Braintree JS SDK already offers Apple Pay support, [see these docs](https://developers.braintreepayments.com/guides/apple-pay/overview). 

If you still have a bug or feature request, please report it to the [Braintree Web GH issues page](https://github.com/braintree/braintree-web/issues). If you need help troubleshooting your specific integration, please contact Support at https://help.braintreepayments.com.

> but apple store not allow to push app with only card payments so I need apple pay subscription

If you have a reference for where you learned this, please do share!

**Comment by crookedneighbor** [comment]
I'm a developer on the Braintree web SDK and just want to jump in here to say that I don't think using the apple pay component in the web SDK will work. That requires you to register a domain with apple, and in the case of Cordova, you don't have a website to register, just an embedded html page in a webview.

> Create app of native framework7 (vue) with dropin braintree Javascript, but apple store not allow to push app with only card payments so I need apple pay subscription in my cordova app.

I'd love to hear more about this, because as far as I understood, if you're doing an in-app purchase, you are not allowed to use anything but the built in app store system for purchases. So you'd need a cordova plugin such as this one to accomplish that: https://github.com/j3k0/cordova-plugin-purchase

If you're not doing an in-app purchase, this is the first I've heard about Apple Pay being required, so I'd love to see some documentation on that. But if you do need to accept apple pay, I believe you'll need to call out to the native ios sdk (this repo) to do so, but you'll have to find a plugin that does that or build one yourself.

Going to leave this closed, for now, because I don't think there's anything for us to do in addition, but would love more information if there is any.

**Comment by patrykKlimczak** [comment]
@crookedneighbor 

Thank you for your answer

I am develop app and the resolve this: on the native app is redirect on website with correct subscription
![image](https://user-images.githubusercontent.com/18028886/100863575-0c88de80-3495-11eb-8109-69622200d5b2.png)

and I have the apple pay button and local tested everything it's okej, but apple have problem with solutions:
![image](https://user-images.githubusercontent.com/18028886/100863642-24606280-3495-11eb-9df3-98942c2cd510.png)

![image](https://user-images.githubusercontent.com/18028886/100863661-2de9ca80-3495-11eb-963e-2081cd6fa282.png)

I think that this solution is logically real and correctly done, but app store supprot has a problem with that. Can it be done differently?

**Comment by scannillo** [comment]
It looks like the email from App Store Review is that you aren't using the in-app purchase API for subscriptions happening in the app. You need to use the[ in-app purchase API ](https://developer.apple.com/in-app-purchase/)for consumables (ex: additional lives in a video game), non-consumables (ex: premium features within an app), and subscriptions to content. 

I think that the note about Apple Pay is separate from the in-app purchase update that is required. It is saying that if your app _also_ sells physical goods, that Apple Pay should be offered.
