### ISSUE TITLE
Providing delivery method ?

### ISSUE THREAD

**Issue by RocKer004** [braintree/braintree_ios#635]
Hi there, is it possible to provide delivery method to Google Pay or Apple pay payments for example ? thanks in advance.

**Comment by sestevens** [comment]
Hi @RocKer004, this sounds like a question about the Google Pay and Apple Pay APIs, rather than the Braintree SDK. For Apple Pay, you can set [`shippingType`](https://developer.apple.com/documentation/passkit/pkpaymentrequest/1619330-shippingtype) and/or [`shippingMethods`](https://developer.apple.com/documentation/passkit/pkpaymentrequest/1619226-shippingmethods) on your `PKPaymentRequest`. I don't see an equivalent on Google Pay's [`PaymentDataRequest`](https://developers.google.com/pay/api/android/reference/request-objects#PaymentDataRequest).

**Comment by sestevens** [comment]
It looks like shipping options can be set in [Google Pay's web API](https://developers.google.com/pay/api/web/reference/request-objects#ShippingOptionParameters), but not the Android API.

**Comment by sestevens** [comment]
I'm going to close out this issue, but feel free to open a new one or contact [Braintree Support](https://help.braintreepayments.com/) if you have any additional questions.

**Comment by RocKer004** [comment]
Hi, thanks for your reply.. for example , for javascript SDK there's an option enableShippingAddress (for paypal) but I don't find an alternative for the mobile version. Can you give me a little hint about this ? 
https://developers.braintreepayments.com/reference/client-reference/javascript/v2/paypal

**Comment by sestevens** [comment]
@RocKer004 Sure! On iOS and Android the equivalent property on the PayPal request objects would be `shippingAddressRequired`. This behaves the same as `enableShippingAddress` in the JavaScript SDK.

**Comment by RocKer004** [comment]
Hi there, thanks for your reply. This was very helpful, I was able to let user select shippingAddress through paypal. Is there any way to let user also select the shipping method there like on Apple/Google pay ? if so, what is the name of the prop ?

**Comment by sestevens** [comment]
For Apple Pay and Google Pay, the shipping address properties belong to those respective APIs (not the Braintree SDK). You can check out the [`PKPaymentRequest`](https://developer.apple.com/documentation/passkit/pkpaymentrequest) docs for Apple Pay and [`PaymentDataRequest`](https://developers.google.com/pay/api/android/reference/request-objects#PaymentDataRequest) docs for Google Pay to see all the available options.
