### ISSUE TITLE
Provide static framework

### ISSUE THREAD

**Issue by shanksGuo** [braintree/braintree_ios#666]
Could you provide static version of all the frameworks?
For us, App launch time is very important, so we want static version of frameworks such as PPRiskMagnes.framework, BraintreePayPal.framework, PayPalDataCollector.framework, BraintreeCore.framework.
We are on 4.x and want to upgrade to 5.x, but the dynamic libraries stopped us. 
Wish you take my suggestion, thanks!

**Comment by sestevens** [comment]
Hi @shanksGuo, this is something we can look into doing as part of our release process. In the meantime, you're welcome to clone this repo and try generating static frameworks yourself. It looks like you could use [Carthage](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md) to do this if you like.

**Comment by shanksGuo** [comment]
@sestevens  appreciate for your response. But, the problem is PPRiskMagnes.framework is a dynamic framework, we want all the frameworks we use are static frameworks.  Is it possible change the "PPRiskMagnes.framework" to static?

**Comment by scannillo** [comment]
Hi @shanksGuo. Our PPRiskMagnes team doesn't provide a static version of that binary. Also - we only officially support integrations through either SPM, CocoaPods, or Carthage. We encourage you use one of those package managers.

---

Also, for what it's worth here is a snippet from the [SPM docs](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html).

> A library’s product can either be statically or dynamically linked. It is recommended to not declare the type of library explicitly to let the Swift Package Manager choose between static or dynamic linking depending on the consumer of the package.

Our SDK does not declare the type of each library, and it seems like SPM is able to do proper optimizations of the frameworks that it can build as either static or dynamic. This might also be true for the other package managers, you would have to research more, but hopefully helps your use case going forward.

**Comment by MattFoley** [comment]
Hi, I was just hoping to re-open this discussion. Is it possible to understand more about what functionality the PPRiskMagnes SDK is supporting? If we were to remove it, what would the implications of that be? 

Does it actually have any internal functionality that requires it be a dynamic framework, rather than just a static library? KountDataCollector.xcframework is a good example, it is packaged as an .xcframework, but internally it's a static library, so it's fine.

Similar to previous responders, my team ships a dynamic framework, and currently [iOS does not support packaging](https://developer.apple.com/forums/thread/128117) nested frameworks inside of other frameworks with .xcframework on iOS, only on MacOS. Our target audience does not typically use things such as CocoaPods, Swift Package Manager or Carthage.
