### ISSUE TITLE
Build & Run function, but SwiftUI previews break app-wide if braintree is installed.

### ISSUE THREAD

**Issue by RamblinWreck77** [braintree/braintree_ios#716]
-Braintree 5.4.3
-BraintreeDropIn 9.1.0
-Both Installed via SPM
-Xcode 12.5.1
-M1/Apple Silicon

1) Make a sample SwiftUI project
2) Add the above
3) Try and run live preview
4) Observe error:

<img width="543" alt="Screen Shot 2021-07-23 at 1 30 14 PM" src="https://user-images.githubusercontent.com/22692130/126819743-0bd25b5e-8601-42c3-9bec-699b4448dae5.png">

**Comment by RamblinWreck77** [comment]
<img width="510" alt="Screen Shot 2021-07-23 at 1 32 50 PM" src="https://user-images.githubusercontent.com/22692130/126820192-e711263d-f594-4743-a0c3-49f3d6e83d2e.png">

How can I get rid of CardinalMobile?

**Comment by RamblinWreck77** [comment]
Any update @mickeyreiss @sestevens, or is it the intention that adding braintree/paypal to your project makes modern iOS/SwiftUI development impossible?

**Comment by RamblinWreck77** [comment]
I get this is coming from a company that ships Objective-Crap code in 2021, as embarrassing as it is integrating your garbage 10 year out of date sdk, I still maintain a minimum level of expectations for paypal when it comes to... charging people money. That's kind of what you do. That should always work. It doesn't work. Fix it.

**Comment by scannillo** [comment]
👋  Hello. Thanks for opening this issue. We are still waiting on CardinalMobile to support M1 (arm64). For SPM, you would have to exclude the `BraintreeThreeDSecure` module entirely to get rid of CardinalMobile. Cardinal is our MPI provider for 3DS 2.0 transactions. You could do this if your app doesn't accept 3DS ... or you could do your development on a real device instead of simulator, for now. While we know these solutions are not great or really acceptable - we have our hands tied by Cardinal right now and are doing our best to get them to add arm64 support.

I am going to close this issue in favor of tracking in the existing issue here --> https://github.com/braintree/braintree_ios/issues/564.
