### ISSUE TITLE
'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

### ISSUE THREAD

**Issue by andesappal** [braintree/braintree_ios#718]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: flutter_braintree: ^2.0.0-nullsafety.0
 - Environment: production
 - iOS Version: 9.0
 - Xcode Version: 12.4
 - Device: any iOS device
 - Integration type & version: COCOAPODS: 1.10.1

**Describe the bug**
Unable to run Product > Archive on Xcode, I get: `'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead`

The app builds and runs without issues on Android Studio and on an Android device. 

**To Reproduce**
I'm unable to give you a minimum working example of the issue without handing out a private codebase. 

**Expected behavior**
The app should be able to be Archived, to be sent to TestFlight. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54340176/127151339-81093022-f5cf-40c2-9321-0396eb6211ce.png)

![image](https://user-images.githubusercontent.com/54340176/127151396-ecd51b91-9df2-4912-8ce3-78f24580cf20.png)

**Comment by scannillo** [comment]
👋  This was fixed in our v5 release of the SDK ([see this GitHub Issue](https://github.com/braintree/braintree_ios/issues/544)).

Also the SDK you are using `flutter_braintree` is not written by Braintree developers and is not officially supported by us. I would encourage you to either contact whoever writes that SDK and have them update the version of Braintree it is using to v5, or to (ideally) directly include the Braintree SDK yourself into your application.

**Comment by andesappal** [comment]
Hi @scannillo thanks for replying. Do you mean ideally I should fork the braintree_ios repo and use it in my app? The only thing we tried which we thought was the closest attempt of fixing was to manually change to v5 on these lines https://github.com/pikaju/flutter-braintree/blob/master/ios/flutter_braintree.podspec#L19-L20

**Comment by andesappal** [comment]
@scannillo which files should I include in my app and where, from braintree_ios?

**Comment by HanzlaRafique** [comment]
Hi @scannillo , I hope you are doing well. Please guide me, I'm facing the same issue while build/run my project. 
I'm using:
- platform :ios, '10.0'
- Xcode Version: 12.5
- Device: Simulator 8,X,12 or Any
- Integration type: CocaPods

Please attached image : <img width="968" alt="Screenshot 2021-12-24 at 1 22 54 AM" src="https://user-images.githubusercontent.com/53652998/147289050-92ae52e7-9ffe-428f-b6a0-879cc7996159.png">
  
Let me know if you required additional information. I'm waiting your kind response.

Thank you

**Comment by sarahkoop** [comment]
Hi @HanzlaRafique - Are you using the `flutter_braintree` library?  If so, please refer to the [issue opened with that library](https://github.com/pikaju/flutter-braintree/issues/77), since we do not own or maintain that library. If you are using the Braintree iOS SDK, please let us know which specific library and version you are using so that we can investigate.
