### ISSUE TITLE
"Braintree/Btclient.h file not found"

### ISSUE THREAD

**Issue by venkativ** [braintree/braintree_ios#80]
I am trying to install braintree sdk using manual integration without using cocoapods. i am getting lexical or preprocessor issue "Braintree/Btclient.h file not found" while running the app.please help me with correct solution

**Comment by bpollock-coursera** [comment]
@venkativ Did you work out a solution? I'm also experiencing this issue.

**Comment by burnto** [comment]
Hi @venkativ @bpollock-coursera - are you following the [manual integration documentation](https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md)?

**Comment by bpollock-coursera** [comment]
@burnto Yep, following that. Only difference is I'm adding braintree to a framework not an app. However, I don't see how that would matter in this case.

**Comment by mickeyreiss** [comment]
@bpollock-coursera 

> Modifying the angle brackets to be quotes for those imports fixed it,

This tells me that your user header search paths are different from your header search paths, and that the former includes the Braintree SDK headers.

Can you show us your user header search paths and your header search paths?

In general, I am wondering if it would be helpful to use the "Always Search User Paths" option. I am also wondering if you tried adding a recursive header search path such as `$(SRCROOT)/Braintree/**`.

**Comment by bpollock-coursera** [comment]
Tried modifying header search paths a ton, but couldn't fix this problem with that approach.

This is what I see after creating a new framework and adding the brain tree files to it in Xcode 6.1.1

Header Search Paths:
$(inherited)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include

![header search paths](https://cloud.githubusercontent.com/assets/8548625/6005595/5facf084-aac0-11e4-829d-bb0d4b37e129.jpg)

**Comment by bpollock-coursera** [comment]
@mickeyreiss @burnto Any update on this?

**Comment by mickeyreiss** [comment]
We have not been able to reproduce this so far. Are you able to upload your project (or a sample project) that fails to build in the way you've described, so that we can take a look?

**Comment by Reflejo** [comment]
@bpollock-coursera That path doesn't seem right but again is impossible to be sure without the project. Make sure to have one entry in your "Library Search Path"  pointing to 
either
`$(SRCROOT)/2.0/Modules/PaymentsModule/BraintreeSDK/Braintree/`
or
`$(SRCROOT)/Modules/PaymentsModule/BraintreeSDK/Braintree/`

(Not sure what your $SRCROOT is in your case). Also make sure that you are importing the library as `#import <Braintree/Braintree.h>` not as a quoted header.

**Comment by bpollock-coursera** [comment]
I created something pretty barebones for you. You can see that I've imported the braintree framework into the FrameworkViewController, but the Braintree cannot find it's headers.

Its too big for GitHub, you can get it here: https://www.dropbox.com/sh/vzbrfk8pzv84qhp/AAAtjX0iydXwAhF-nTkAQA0Da?dl=0

**Comment by bpollock-coursera** [comment]
@Reflejo @mickeyreiss Any update on this? We will need to start moving with this SDK soon and I don't want to fork the repo.

**Comment by mickeyreiss** [comment]
Sorry, no update yet. I'll look into it today and let you know.

**Comment by Reflejo** [comment]
@bpollock-coursera Oh, I didn't know it was a swift project. Are you planning on using embedded frameworks? (As in: Do you need iOS7 support?)

**Comment by mickeyreiss** [comment]
@bpollock-coursera I was able to fix the the `BraintreeSDK` build by renaming the target to `Braintree` and [adding two missing `@import` statements](https://github.com/braintree/braintree_ios/commit/ad3df7059426a5f50dff499a046a4d2fed0e1f8f).

I am now unable to build `exampleFramework` due to a relatively opaque swift error: `could not build Objective-C module 'Braintree`.

Before I continue, which version of Xcode are you trying to use? I am still on Xcode 6.1, but I know the latest 6.3 beta brings some significant changes in the swift compiler.

([Here](https://www.dropbox.com/sh/z23vzipl4epofee/AAAxFXkRUPiJ1FQSdgmrxvq-a?dl=0) are some screenshots of what I'm seeing.)

**Comment by Reflejo** [comment]
The root of the problem lies on two factors (third if we count the missing @import UIKit; that @mickeyreiss  fixed):

1) All the system imports (imports using <>) are expecting a framework named Braintree, that's why when @mickeyreiss renamed the target `BraintreeSDK` to `Braintree`, suddenly the missing header errors disappeared.

2) The problem now is that in order to make Braintree (or any other library for that matter) a module you need two things: a) A modulemap (because you want to specify a custom umbrella) and b) an umbrella header.

    2.1 Inside the umbrella header, you have to add all public facing .h files as imports.
    2.2 All the .h that you include in the umbrella framework and all the .h that those files include, need to be set as Public on xcode (Braintree target -> Build Phases -> Headers)

Once you do that you should be able to compile it. Here is a working version of your project: https://www.dropbox.com/s/9nzi6zu36jcdtsi/exampleModule-working.zip?dl=0

**Comment by mickeyreiss** [comment]
Wow! Thanks for sharing your findings, @Reflejo.

Is there anything we could do to make integrations like this easier? Should we add to the manual integration instructions?

**Comment by Reflejo** [comment]
@mickeyreiss There is nothing particularly wrong on the Braintree SDK, the process to manually create a target/module is just painful, *per se*, when you try to do it manually. One thing you guys can do is compile a ready-to-use SDK with the `modulemap` inside and distribute the compiled .framework for those who want to manually include Braintree. 

Having said that, I'd strongly recommend everyone to use CocoaPods tho, which solves all these problems for you.

**Comment by mickeyreiss** [comment]
Phew, I'm glad you suggested CocoaPods. This is exactly why we elected to go with CocoaPods as our primary integration method, even in its pre-1.0 days.

**Comment by bpollock-coursera** [comment]
Thanks a lot @Reflejo with those directions + example project I was able to get things building. 

@mickeyreiss I think it would be good to update the manual instructions since #swiftIsTheFuture. CocoaPods is great for certain use cases, but in the past hasn't supported dynamic frameworks and modifies your workspace in uncontrollable ways. We want to control our build environment which is why we moved away from it.

**Comment by bpollock-coursera** [comment]
@Reflejo are you able to run it on device? I'm able to run on sim, but Xcode hangs when I try to run it on device and the app never launches. CC @mickeyreiss

**Comment by mickeyreiss** [comment]
@bpollock-coursera I totally empathize. I've also been thinking about and exploring how to take on swift in the future. If I were making a new app today, I'd strongly consider swift as well.

As a company, Braintree isn't ready to take on the responsibility of supporting yet another platform natively quite yet. That being said, I've gone through [an exploration](https://github.com/mickeyreiss/braintree-swift) to see what a native swift lib might look like and am generally collecting feedback to inform the next major revision of the SDK.

Great idea to add a few words about frameworks/swift in the manual instructions. I'll add that to our backlog.

**Comment by bpollock-coursera** [comment]
@mickeyreiss does this mean not to expect support on this bug: Understanding why adding the Braintree SDK hangs Xcode is not usable on a physical device?

**Comment by Reflejo** [comment]
@bpollock-coursera I think what he meant is not that they won't help you but rather that they can't rewrite the SDK on swift just yet.

I'm not in front of my laptop right now but I'll try to build your project on the device later. What I can tell you is: I'm using Braintree from a swift project and it works, so if it's not your Xcode then there is something wrong in the project and it should be fixable. One thing you can do in the meantime is create a sample project using cocoapods, include Braintree as a framework and compare the settings of the Braintree target with yours.

**Comment by mickeyreiss** [comment]
> @bpollock-coursera I think what he meant is not that they won't help you but rather that they can't rewrite the SDK on swift just yet.

Exactly right.

> @mickeyreiss does this mean not to expect support finishing up this bug?

I'm happy to help. Keep in mind that the primary way we use Github issues is to identify and fix issues in the SDK codebase.

> i.e. Understanding why adding the Braintree SDK hangs Xcode is not usable on a physical device.

I have not seen or encountered the issue you're describing. Can you please provide a sample project or more steps to reproduce?

**Comment by bpollock-coursera** [comment]
Thanks @mickeyreiss and @Reflejo just wanted to be clear on the message.

@Reflejo Are you embedding the Braintree framework directly in your app or are you building it into a framework that is included in your app as in this case.

@mickeyreiss you can reproduce on @Reflejo's project above by running on a device.
"Once you do that you should be able to compile it. Here is a working version of your project: https://www.dropbox.com/s/9nzi6zu36jcdtsi/exampleModule-working.zip?dl=0"

**Comment by dsieczko** [comment]
@Reflejo Thanks a bunch. I got everything working as it should in my first Swift project - first app, web or otherwise, for that matter  - I did as you suggested except inside the umbrella header file I removed the card.io headers as they aren't inside the sdk as of right now and I added the beta 3D-Secure headers.

**Comment by burnto** [comment]
We [updated the manual integration instructions extensively](https://github.com/braintree/braintree_ios/compare/bf79530d79eb8af7ed77a81f55a838be1a19a53d...967c3bcb7a40133068c0d1b74b7878a3dc614e1e?name=967c3bcb7a40133068c0d1b74b7878a3dc614e1e&short_path=434c121#diff-434c12160e2d38466541e8f860f4623e), and this issue with header search paths should now be addressed (as well as other manual integration issues). Make sure to follow [step 7](https://github.com/braintree/braintree_ios/blob/967c3bcb7a40133068c0d1b74b7878a3dc614e1e/Docs/Manual%20Integration.md) and set `Always Search User Paths` to `Yes`.

Please reply here if you feel further discussion is warranted. Thanks all!
