### ISSUE TITLE
- `Braintree/Apple-Pay` required by `Podfile`

### ISSUE THREAD

**Issue by chaitubndr07** [braintree/braintree_ios#91]
Hi,

I installed Braintree using pods.
Later I updated pod file with pod 'Braintree/Apple-Pay'

When I run "pod install"

I am facing an error 
[!] Unable to satisfy the following requirements:
- `Braintree/Apple-Pay` required by `Podfile`

Attached image taken from terminal.
What should I do to implement Apple-pay using braintree.
![screen shot 2015-02-14 at 3 54 59 pm](https://cloud.githubusercontent.com/assets/5868061/6199307/e7ca0c22-b461-11e4-941c-b6669bd0411d.png)

Thanks,
...

**Comment by mickeyreiss** [comment]
I believe the issue here is that we have not yet released version 3.6.0, which will be the first version to include the `Braintree/Apple-Pay` subspec.

We expect to tag and release 3.6.0 today or tomorrow.

You could also start to integrate the previous version, 3.5.0, which does not require the Apple-Pay subspec to use Apple Pay.

Feel free to reopen this issue or email support@braintreepayments.com if you still have questions!
