### ISSUE TITLE
TokenizeVenmoAccount callback is not invoked

### ISSUE THREAD

**Issue by Dmitry-Pliushchai** [braintree/braintree_ios#953]
### Braintree SDK Version

5.20.1

### Environment

Sandbox

### Xcode Version

14.2

### OS Version & Device

16.0

### Integration type

Swfit Package Manager

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

I faced the issue that TokenizeVenmoAccount callback is not invoked after obtaining response from venmo test app despite venmo test app opens app with correct url with nonce. It works fine in your demo app but it doesn't work in my project and I have no idea what I am missing after investigation.

### To reproduce

Launch example app [TestVenmo.zip](https://github.com/braintree/braintree_ios/files/10702312/TestVenmo.zip)

### Expected behavior

TokenizeVenmoAccount callback is invoked after obtaining response from venmo

**Comment by scannillo** [comment]
👋 Hello @Dmitry-Pliushchai - thanks for opening this issue and using the Braintree iOS SDK.

Adding the [`onOpenURL(perform:)`](https://developer.apple.com/documentation/swiftui/outlinesubgroupchildren/onopenurl%28perform:%29) modifier to your `ContentView`, and calling `BTAppContextSwitcher.handleOpenURL` should fix the issue. Like this:
```
.onOpenURL { (url) in
    BTAppContextSwitcher.handleOpenURL(url)
}
```

This is definitely an oversight on our end, since our public docs don't currently include SwiftUI-specific instructions for [this step](https://developer.paypal.com/braintree/docs/guides/venmo/client-side/ios/v5#handle-app-context-switching). 

Let us know if this resolves your issue and we will be sure to update our docs!

**Comment by Dmitry-Pliushchai** [comment]
Thanks for quick response. It works like a charm, thanks a lot.
